### ISSUE TITLE
在tag中，比如head tag中用block 报错

### ISSUE THREAD

**Issue by atlas1119** [scrat-team/nunjucks-pagelet#16]
用extend 时，用block时报
![Uploading 11111.png…]()

**Comment by atlas1119** [comment]
Template render error: (unknown path)
[1]     Template render error: (/Users/wsj/project/red-all/main/main-site/static/pc_site/html/header/head.tpl)
[1]     Error: unknown block "title"
[1]       at Object.exports.prettifyError (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/lib.js:34:15)
[1]       at /Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:485:31
[1]       at [object Object].root [as rootRenderFunc](eval at <anonymous> %28/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24%29, <anonymous>:78:3)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:36:16)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:31:46)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:31:81)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:27:46)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:27:86)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:23:46)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:23:82)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:19:46)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:19:90)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:15:46)
[1]       at eval (eval at <anonymous> (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:15:87)
[1]       at [object Object].Obj.extend.getTemplate (/Users/wsj/project/red-all/main/main-site/node_modules/nunjucks/src/environment.js:194:17)

**Comment by atian25** [comment]
related https://github.com/mozilla/nunjucks/pull/784
